giaipt: PhuongTrinhBac1.o GiaiPhuongTrinh.o
	gcc -o giaipt PhuongTrinhBac1.0 GiaiPhuongTrinh.o
GiaiPhuongTrinh.o: GiaiPhuongTrinh.cpp
	gcc -o GiaiPhuongTrinh.o -c GiaiPhuongTrinh.cpp
PhuongTrinhBac1.o: PhuongTrinhBac1.cpp
	gcc -o PhuongTrinhBac1.o -c PhuongTrinhBac1.cpp
clean:
	rm *.o *~